name: CI
on:
  pull_request:
    branches:
      - main
    paths:
      - 'main.go'
      - 'go.mod'
      - 'go.sum'
      - 'internal/**'
      - '.github/workflows/ci.yaml'
  push:
    branches:
      - main
    paths:
      - 'main.go'
      - 'go.mod'
      - 'go.sum'
      - 'internal/**'
      - '.github/workflows/ci.yaml'
jobs:
  test:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
      - name: Download Dependencies
        run: go mod tidy
      - name: Test
        run: go test -v ./...
